// <auto-generated />
using BensBlazorWebAssembly.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BensBlazorWebAssembly.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241014153139_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BensBlazorWebAssembly.Common.Entities.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = 18,
                            Genre = "Shooter",
                            Platform = 6,
                            Title = "Halo"
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 3,
                            Genre = "Platformer",
                            Platform = 8,
                            Title = "Mario"
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriction = 18,
                            Genre = "Action",
                            Platform = 4,
                            Title = "God of War"
                        },
                        new
                        {
                            Id = 4,
                            AgeRestriction = 12,
                            Genre = "Battle Royale",
                            Platform = 9,
                            Title = "Fortnite"
                        },
                        new
                        {
                            Id = 5,
                            AgeRestriction = 7,
                            Genre = "Sandbox",
                            Platform = 1,
                            Title = "Minecraft"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
